### PR TITLE
send invite email reminder if user hasn't confirmed account after 3 days & 1 week & 3 weeks

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Comment by chime-mu** [comment]
@jlopker Tests fail.

**Comment by jlopker** [comment]
@chime-mu fixed tests!

**Comment by chime-mu** [comment]
@jlopker The code looks good. Have you done anything to test this?

**Comment by jlopker** [comment]
@chime-mu i've tested it locally with mailcatcher. do you think there's some other way I should be testing it?

**Comment by chime-mu** [comment]
@jlopker I was mostly wondering how you tested the time aspect - that all 3 mails actually get sent, at the specified time.

It doesn't make sense to let the test take 3 weeks, so one way to test would be to make the time interval configurable and then run a test that verifies they actually do get send. Another option would be to make a testbot that test it works with the real time intervals on the production system. 

Or maybe something else?

**Comment by jlopker** [comment]
@chime-mu ah i see- yea i made the time really short and saw that they got sent. and then just increased the time. i figured it was a reasonable way to test it.. what do you think?

**Comment by chime-mu** [comment]
@jlopker Agree that it will work for now.

**Pull request merged**
