### PR TITLE
post to /archive can now handle unarchiving

### PR DESCRIPTION
**Pull request by jlopker**

### CODE REVIEW

**Comment by chime-mu** [comment]
As fas as I understand the way to unarchive the bucket is simply the same call as archiving a bucket, but if it's already archived, it will be unarchived.

I think there's drawback to this solution as the API call is not idempotent. If a call fails and we get no reply, we can't retry, because we no longer know what state the bucket is in.
Thus I would prefer an idempotent solution. This could one of:
a) Use another URL for unarchiving 
b) Pass a parameter specifying if the state should be archived or not.

**Comment by chime-mu** [comment]
In membership_service.rb, line 9-11: When a member is archived, Bucketservice.archive is called for all buckets that aren't funded. Don't we risk that previously archived buckets, will suddenly become unarchived?

**Comment by chime-mu** [comment]
We should probably update the test-suite for unarchiving. Or what do you think?

**Comment by jessykate** [comment]
i agree we should start adding tests. since we don't have any kind of front end test infrastructure in place yet though, i think it makes sense to leave this to a dedicated [ticket](https://waffle.io/cobudget/cobudget/cards/58cd5ba138c7ff1c00ff7a59), and consider prioritizing that for next sprint. how does that feel to y'all?

**Comment by jessykate** [comment]
question: what happens if bucket.update fails? i _think_ if the method raises an error then the API returns a 500 by default. do we want to do anything more special?

as a bonus i would say we should add a test for this, but if not please add a ticket to make one next sprint. in general though, i guess we should be starting to write the tests as part of the tickets themselves. feels about that? 👼

**Comment by chime-mu** [comment]
There's already a very strong test suite in the api project (coverage > 90%), so it would be sad not to maintain that. I think it would be great to define a  _definition of done_ so that we agree what we should do for alle tickets.

I think the "how much should we test" is a really interesting question - and also I can of worms. But the existing testsuite has already to proved to be very valuable.

I'll approve and merge this and create a ticket for adding the test.

**Pull request merged**
