### PR TITLE
added bitcoin and ethereum

### PR DESCRIPTION
**Pull request by jlopker**
there is a UI PR as well

### CODE REVIEW

**Comment by jlopker** [comment]
there is a UI PR for this as well

**Comment by chime-mu** [comment]
Let's not do this until we fully understand how to handle subunits like milli, micro etc.

**Comment by chime-mu** [comment]
@jlopker We should either merge this or delete the branch. Since I think we're not really ready for Crypto support I'm tempted to delete. What do you think?

**Comment by jlopker** [comment]
@chime-mu i'm happy to delete. would not be a problem to re-implement

**Pull request closed without merging**
