### PR TITLE
WIP intentional saving

### PR DESCRIPTION
**Pull request by jessykate**
requires migration. add new field `saved_funds_at` on membership. add new route for a csv download called 'report' which will include info on last time a user saved their funds. this report can also be extended to add info admins have been asking for such as a report on which active and paid buckets a user has funds in.

### CODE REVIEW

**Comment by chime-mu** [comment]
Fran suggested that logging in to cobudget should be sufficient to acknowledge intentional non-spending and I agree. If you're in the tool and not doing anything, you're actually intentionally non-spending. So maybe we need no button? 

I think that could work.

**Comment by jessykate** [comment]
ok @jlopker and i had a long chat about this today. i have posted on the original loomio thread to inquire whether peeps think it's sufficient. it seems neither are perfect but we ultimately came around to agreeing the last-logged-in time was probably equally imprecise in different ways, but involved less changes. so we're going with that. 

our new thinking is as follows:

* expose the (existing) last logged in date to admins, on the funders tab, next to the user's name
* add a method on the backend to generate email reminders about unspent funds users
* allow admins to manually send that reminder to user's, through an option on the right click menu for that user
* also have automatic emails go out every 30 days to users who have not logged in within that timeframe
  * don't build an interface to customize this frequency _yet_ -- wait to see if people ask for it. 
  * but DO respect individual users' email settings, so if they have turned off emails they will not receive the reminders. 

we're going to swarm on the new feature announcement ticket first, tomorrow morning, and then i'll come back to this ticket. 

thoughts on this new approach?

**Comment by chime-mu** [comment]
I think that's a great solution 👍 

Given there are more things we want to do in this sprint and given the original story was about giving the user the ability to indicate intentional non-spending I think the whole sending out automatic mails is a different story and we could choose to put that on the backlog for the next sprint.

**Comment by chime-mu** [comment]
@jlopker It seems the PR and branch is abandoned and not needed anymore. Are you ok with deleting PR and branch?

**Comment by jlopker** [comment]
@chime-mu yep this feature is not something we are actively wanting to build. happy for you to delete!

**Pull request closed without merging**
