### PR TITLE
model testing

### PR DESCRIPTION
**Pull request by euglazer**
wrote a bunch of model tests as a first step towards getting my head around this api

### CODE REVIEW

**Comment by ahdinosaur** [comment]
looks good to me.

**Comment by derekrazo** [comment]
yeaah!! :dancers: GJ guys

**Comment by jonlemmon** [comment]
Hey Eugene, cool!!! Great to see you contributing here. :)

I noticed your editor might have been set to indent with tabs instead of spaces for some of the files? Generally all ruby code is written with 2 spaces for indentation (tabs are considered evil).

Also, [Warning: strong personal perspective about to be voiced] I may have mentioned this to you before, but I think "shoulda" tests are a waste of time. Especially when the code in the model looks pretty much identical to what you're writing in the test. Like, what is that testing really? Does it make you feel anymore confident about what you're coding? I know it doesn't for me.

Kent Beck said, "I get paid for code that works, not for tests, so my philosophy is to test as little as possible to reach a given level of confidence... If I don’t typically make a kind of mistake (like setting the wrong variables in a constructor), I don’t test for it." 

So like, testing simple validations, really? I recommend giving both these articles from DHH (the creator of Rails) a read:

http://david.heinemeierhansson.com/2014/test-induced-design-damage.html
http://signalvnoise.com/posts/3159-testing-like-the-tsa

I used to think DHH was a dick and not worth listening to ([here's some slightly embarrassing proof](https://twitter.com/jon_lemmon/status/284075141967790080)), but then I read those posts and they totally changed the way I work. I used to try to test everything perfectly. But something always felt not-quite-right. I couldn't quite put my finger on it, but then I read those articles, and I realized that somewhere early on in my programming career I had, without much consideration, joined "The Church Of TDD". Judging by your pull request, I think you may have joined it too. I guess you were raised in it, so who could blame you? There are so many people who you love and trust telling you that it's the one single truth that you must follow. But speaking as someone who was a part of that church and then left, trust me man, it's way better out here!

Once you stop religiously unit testing everything you start working way quicker and you write better code because you're more focused on what actually matters. When you DO write unit tests, it's because you've come across something tricky and you need a bit of help, and it feels REALLY GOOD to write the tests, because you're using them in the correct context. (Note that I'm speaking about *unit* tests here. I still write integration tests for every API point. They are quick to write and they give me a lot of confidence about the entire system.)

One thing Rob Guthrie used to always tell me when I was getting stuck on a particular test was "Does it feel like this test is helping you right now or holding you back? If it's holding you back, just delete it and move on." Rob was constantly encouraging me to delete tests and not worry about replacing them right away. It was good advice, but it was often hard for me to swallow.

Now that I've left the Church, I've noticed that there is a real art in deciding what to test, when to refactor, etc. I think this goes against our nature as engineers. We want to do something the same way every time, follow the rules religiously, and keep everything super consistent. But actually, good programming is equal parts art and science. If you apply the rule that "absolutely everything must be unit tested", you take away the art. Be organized and systematic, but fight the urge to apply a single rule to every situation. Trust your instincts. That's the most important thing I've learned in programming. If something doesn't feel right, don't be afraid to break the rules and do something different. Program like a human, not a machine. The art comes first, then the science.

**Comment by derekrazo** [comment]
@jonlemmon - damn thanks so much for that. I think this is a really really valuable perspective to integrate. Glad you could share some of your experience here. :)

**Comment by euglazer** [comment]
@jonlemmon 

thx for the perspective and for the articles! 

i'm using these tests less as 'tests' and more as a quick reference for future contributors and myself. it's nice seeing all the cobudget models, with their fields, associations, validations, and methods, all in one place, whenever I need, just by running 'bundle exec rspec'.

**Comment by euglazer** [comment]
also great seeing all your request specs, which have totally helped me understand your code. thanks for that!

**Comment by jonlemmon** [comment]
yeah sweet! in that case, totally go for it!! seems like a great way to get to know the codebase. just don't be afraid to mercilessly rip them out when they aren't helping you anymore. :)

**Pull request merged**
