### PR TITLE
Change group account from membership to an account on Group

### PR DESCRIPTION
**Pull request by chime-mu**

### CODE REVIEW

**Comment by chime-mu** [comment]
@jlopker The tests are failing - maybe something in your latest merge?

**Comment by jlopker** [comment]
@chime-mu yep sorry the schema version number was wrong. all fixed now!

**Comment by chime-mu** [comment]
*Release reminder*

* Run DB migration

**Comment by chime-mu** [comment]
# To test

1. As admin create new user and give funds
2. As admin create new bucket
3. As new user, fund the bucket
4. As admin delete the new user
5. As admin cancel the new bucket
6. Verify the amount funded by the new user is now in the group account
7. As admin verify I can move the money from the group account to a different user / myself

**Pull request merged**
